language: python
python:
  - "3.5"

services:
  - postgresql

# setup environment
env:
  - DJANGO_VERSION=2.0.1


install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter


script:
  - export DJANGO_SECRETKEY=secret
  - coverage run --source='.' --omit='*migrations*' manage.py test planner

after_script:
  - codeclimate-test-reporter --file .coverage