language: python
python:
  - "3.5"
  - "3.6"

services:
  - postgresql

# setup environment
env:
  - DJANGO_VERSION=2.0.1
  global:
    - CC_TEST_REPORTER_ID=6a1ffb3e6b4f9d3164103e467bc73d0f92f32fbb

install:
  - pip install -r requirements.txt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to run tests
script:
  - python manage.py test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT