language: python
python:
  - "3.5"

services:
  - postgresql

# setup environment
env:
  - DJANGO_VERSION=2.0.1


install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter

# command to run tests
script:
  - export DJANGO_SECRETKEY=secret
  - coverage run --source=planting_planner manage.py test
  - python manage.py test

after_script:
  - codeclimate-test-reporter --file .coverage