# Generated by Django 3.2.2 on 2021-05-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Espèce')),
            ],
        ),
        migrations.CreateModel(
            name='BaseVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Variétée')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.basespecies')),
            ],
        ),
        migrations.CreateModel(
            name='BaseOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Opération')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.basevariety')),
            ],
            options={
                'unique_together': {('name', 'variety')},
            },
        ),
    ]
