# Generated by Django 3.2.2 on 2021-05-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryOperation',
            fields=[
                ('baseoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.baseoperation')),
            ],
            bases=('common.baseoperation',),
        ),
        migrations.CreateModel(
            name='LibrarySpecies',
            fields=[
                ('basespecies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basespecies')),
            ],
            bases=('common.basespecies',),
        ),
        migrations.CreateModel(
            name='LibraryVariety',
            fields=[
                ('basevariety_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basevariety')),
            ],
            bases=('common.basevariety',),
        ),
    ]
