# Generated by Django 3.2.2 on 2021-05-16 15:08

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'default_related_name': 'beds'},
        ),
        migrations.AlterModelOptions(
            name='garden',
            options={'default_related_name': 'gardens'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'default_related_name': 'observations'},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'default_related_name': 'parcels'},
        ),
        migrations.AlterModelOptions(
            name='performedoperation',
            options={'default_related_name': 'performed_operations'},
        ),
        migrations.AlterField(
            model_name='bed',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='planner.garden'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='bed',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='planner.parcel', verbose_name='Parcelle'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='users',
            field=models.ManyToManyField(related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='historyitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='observations', serialize=False, to='planner.historyitem'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='planner.garden'),
        ),
        migrations.AlterField(
            model_name='performedoperation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_operations', to='planner.operation'),
        ),
    ]
