# Generated by Django 3.2.2 on 2021-08-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('planner', '0003_auto_20210517_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='performedoperation',
            name='variety',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='performed_operations', to='common.basevariety'),
            preserve_default=False,
        ),
    ]
