# Generated by Django 3.2.2 on 2021-08-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_performedoperation_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performedoperation',
            name='operation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='performed_operations', to='planner.operation'),
        ),
    ]
