# Generated by Django 3.2.2 on 2021-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_performedoperation_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='performedoperation',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='performedoperation',
            name='number_of_worker',
            field=models.IntegerField(default=1),
        ),
    ]
