# Generated by Django 3.2.2 on 2021-08-24 09:15

from django.db import migrations, models
from datetime import date


def extract_date(apps, schema_editor):
    PerformedOperation = apps.get_model('planner', 'performedoperation')
    for operation in PerformedOperation.objects.all():
        operation.date = operation.start_time.date()
        operation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20210819_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='performedoperation',
            name='date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.RunPython(extract_date),
        migrations.AlterField(
            model_name='performedoperation',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='performedoperation',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
