# Generated by Django 3.2.2 on 2021-09-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20210824_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.bed')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.vegetable', verbose_name='Légume cultivé')),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='area_concerned',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='history',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='historyitem_ptr',
        ),
        migrations.DeleteModel(
            name='CultivatedArea',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='HistoryItem',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.AddConstraint(
            model_name='plantation',
            constraint=models.CheckConstraint(check=models.Q(('area__gt', 0)), name='planner_plantation_greater_than_0'),
        ),
    ]
