# Generated by Django 3.2.2 on 2021-09-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('planner', '0009_auto_20210902_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantation',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.basevariety', verbose_name='Légume cultivé'),
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
