# Generated by Django 3.2.2 on 2021-09-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('planner', '0011_rename_vegetable_plantation_variety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'default_related_name': 'beds', 'ordering': ['parcel_id', 'index']},
        ),
        migrations.AlterModelOptions(
            name='plantation',
            options={'default_related_name': 'plantations'},
        ),
        migrations.AddField(
            model_name='bed',
            name='index',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantation',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantations', to='planner.bed'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantations', to='common.basevariety', verbose_name='Légume cultivé'),
        ),
    ]
