# Generated by Django 3.2.2 on 2021-09-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20210906_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'base_manager_name': 'objects', 'default_related_name': 'beds', 'ordering': ['parcel_id', 'index']},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'base_manager_name': 'objects', 'default_related_name': 'parcels'},
        ),
        migrations.AlterModelOptions(
            name='performedoperation',
            options={'base_manager_name': 'objects', 'default_related_name': 'performed_operations'},
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.garden')),
            ],
        ),
    ]
