# Generated by Django 3.1 on 2020-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20180531_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='geometry',
            field=models.JSONField(null=True),
        ),
    ]
